'use strict';
/**
 * DUM-E brand mark — a robot arm on the arc-reactor blue tile.
 *
 * THE SVG IS THE SOURCE OF TRUTH. Every raster is generated from the same
 * geometry, never traced back from a PNG. Adapted from the upstream mark
 * pipeline (tools/make-logo.cjs in Munder Difflin): same run-merged <rect>
 * approach, same rasteriser — new sprite, new palette.
 *
 * Writes, from one source:
 *   src/renderer/src/brand/logo.svg   source of truth (full bleed, ink border)
 *   src/renderer/src/brand/logo.png  512 — in-app favicon + splash
 *
 *   node tools/make-logo.cjs
 */

const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');

const ROOT = path.resolve(__dirname, '..');
const BRAND = path.join(ROOT, 'src/renderer/src/brand');
fs.mkdirSync(BRAND, { recursive: true });

// ── palette ───────────────────────────────────────────────────────────────
const GROUND = [38, 111, 214];   // #266FD6 — arc-reactor blue
const GOLD   = [244, 211, 94];   // #F4D35E — DUM-E gold accent
const WHITE  = [250, 248, 244];
const INK    = [26, 19, 32];     // #1A1320

const BORDERS = { ink: [26, 19, 32], warm: [12, 56, 122] };

// Tile geometry (same ratios as upstream so the mark lands in the same family)
const R_RADIUS = 144 / 800;
const R_STROKE = 26 / 800;
const FRAMES = { mark: 0, icon: 0 };

// ── sprite ────────────────────────────────────────────────────────────────
// DUM-E: a chunky robot bust, hand-authored 18×28 pixel grid.
// Rows 1-12 head (screen-face + antenna), 13-16 neck, 17-24 chest + arm stub,
// 25-28 base. Drawn as [x, y] runs so every pixel stays square.
const SW = 18, SH = 28;

/** One rect per contiguous horizontal run: [x, y, len, [r,g,b]] */
const RUNS = [
  // antenna
  [8, 1, 2, INK],
  [9, 0, 1, GOLD],
  // head shell
  [4, 2, 10, INK],
  [3, 3, 12, INK],
  [3, 4, 12, INK],
  // face screen
  [5, 5, 8, WHITE],
  [4, 6, 10, WHITE],
  [4, 7, 10, WHITE],
  [4, 8, 10, WHITE],
  [5, 9, 8, WHITE],
  // eyes (blink-free, dead-centre)
  [6, 6, 2, INK],
  [10, 6, 2, INK],
  // mouth grille
  [7, 8, 4, INK],
  // head shell bottom
  [3, 10, 12, INK],
  [4, 11, 10, INK],
  // neck
  [6, 12, 6, INK],
  [7, 13, 4, INK],
  // shoulders
  [2, 14, 14, INK],
  [1, 15, 16, INK],
  [1, 16, 16, INK],
  // chest plate with arc-reactor glow
  [2, 17, 14, INK],
  [7, 18, 4, GOLD],
  [7, 19, 4, GOLD],
  [6, 20, 6, GOLD],
  [6, 21, 6, GOLD],
  [7, 22, 4, GOLD],
  [2, 17, 3, WHITE], [13, 17, 3, WHITE],
  [2, 18, 2, WHITE], [14, 18, 2, WHITE],
  [2, 19, 2, WHITE], [14, 19, 2, WHITE],
  [2, 20, 2, WHITE], [14, 20, 2, WHITE],
  [2, 21, 2, WHITE], [14, 21, 2, WHITE],
  [2, 22, 2, WHITE], [14, 22, 2, GOLD],
  // base
  [2, 23, 14, INK],
  [3, 24, 12, INK],
  [4, 25, 10, INK],
  [5, 26, 8, INK]
];

function buildGrid() {
  const cells = [];
  for (const [x, y, len, c] of RUNS) {
    for (let i = 0; i < len; i++) cells.push({ gx: x + i, gy: y, c });
  }
  const xs = cells.map((c) => c.gx), ys = cells.map((c) => c.gy);
  return {
    gw: SW, gh: SH, cells,
    x0: Math.min(...xs), x1: Math.max(...xs) + 1,
    y0: Math.min(...ys), y1: Math.max(...ys) + 1
  };
}

/** Place the grid in the tile at an INTEGER scale, bleeding off the bottom. */
function layout(N, grid, frame) {
  const margin = N * FRAMES[frame];
  const tile = { x: margin, y: margin, w: N - 2 * margin, h: N - 2 * margin };
  tile.r = tile.w * R_RADIUS;
  const stroke = tile.w * R_STROKE;
  const scale = Math.max(1, Math.round((tile.w * (140 / 240)) / (grid.x1 - grid.x0)));
  const drawnW = (grid.x1 - grid.x0) * scale;
  return {
    tile, stroke, scale,
    ox: Math.round(tile.x + (tile.w - drawnW) / 2 - grid.x0 * scale),
    oy: Math.round(tile.y + tile.h * (12 / 240) - grid.y0 * scale)
  };
}

// ── SVG ───────────────────────────────────────────────────────────────────
function buildSvg(N, grid, frame, border) {
  const L = layout(N, grid, frame);
  const t = L.tile, s = L.stroke;
  const rx = t.x + s / 2, ry = t.y + s / 2, rw = t.w - s, rh = t.h - s, rr = t.r - s / 2;
  const body = grid.cells.map((c) => {
    const x = L.ox + c.gx * L.scale, y = L.oy + c.gy * L.scale;
    return `    <rect x="${x}" y="${y}" width="${L.scale}" height="${L.scale}" fill="${hex(c.c)}"/>`;
  }).join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${N}" height="${N}" viewBox="0 0 ${N} ${N}" shape-rendering="crispEdges">
  <!-- DUM-E — the brand mark. Generated by tools/make-logo.cjs; edit that, not this. -->
  <title>DUM-E</title>
  <defs>
    <clipPath id="tile">
      <rect x="${rx}" y="${ry}" width="${rw}" height="${rh}" rx="${rr}"/>
    </clipPath>
  </defs>
  <g clip-path="url(#tile)">
    <rect x="${rx}" y="${ry}" width="${rw}" height="${rh}" fill="${hex(GROUND)}"/>
${body}
  </g>
  <rect x="${rx}" y="${ry}" width="${rw}" height="${rh}" rx="${rr}"
        fill="none" stroke="${hex(border)}" stroke-width="${s}" shape-rendering="geometricPrecision"/>
</svg>
`;
}

const hex = (c) => '#' + c.map((v) => v.toString(16).padStart(2, '0')).join('').toUpperCase();

// ── PNG ───────────────────────────────────────────────────────────────────
const CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return (buf) => {
    let c = -1;
    for (let i = 0; i < buf.length; i++) c = t[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
    return (c ^ -1) >>> 0;
  };
})();

function chunk(type, data) {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(CRC(td));
  return Buffer.concat([len, td, crc]);
}

function encodePng(N, rgba) {
  const stride = N * 4 + 1;
  const raw = Buffer.alloc(N * stride);
  for (let y = 0; y < N; y++) {
    raw[y * stride] = 0;
    rgba.copy(raw, y * stride + 1, y * N * 4, (y + 1) * N * 4);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(N, 0); ihdr.writeUInt32BE(N, 4);
  ihdr[8] = 8; ihdr[9] = 6;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0))
  ]);
}

/** Signed distance to a rounded rect — negative inside. */
function sdRoundRect(px, py, x, y, w, h, r) {
  const cx = x + w / 2, cy = y + h / 2;
  const qx = Math.abs(px - cx) - (w / 2 - r), qy = Math.abs(py - cy) - (h / 2 - r);
  const ax = Math.max(qx, 0), ay = Math.max(qy, 0);
  return Math.hypot(ax, ay) + Math.min(Math.max(qx, qy), 0) - r;
}

const SS = 4;

function rasterise(N, grid, frame, border) {
  const L = layout(N, grid, frame);
  const t = L.tile, s = L.stroke;
  const rx = t.x + s / 2, ry = t.y + s / 2, rw = t.w - s, rh = t.h - s, rr = t.r - s / 2;

  const at = new Map(grid.cells.map((c) => [c.gy * grid.gw + c.gx, c.c]));
  const spriteAt = (px, py) => {
    const gx = Math.floor((px - L.ox) / L.scale), gy = Math.floor((py - L.oy) / L.scale);
    return at.get(gy * grid.gw + gx) ?? null;
  };

  const out = Buffer.alloc(N * N * 4);
  for (let y = 0; y < N; y++) {
    for (let x = 0; x < N; x++) {
      let cov = 0, ink = 0, rSum = 0, gSum = 0, bSum = 0;
      for (let sy = 0; sy < SS; sy++) {
        for (let sx = 0; sx < SS; sx++) {
          const px = x + (sx + 0.5) / SS, py = y + (sy + 0.5) / SS;
          const d = sdRoundRect(px, py, rx, ry, rw, rh, rr);
          if (d > s / 2) continue;
          cov++;
          if (d > -s / 2) { ink++; continue; }
          const c = spriteAt(px, py) ?? GROUND;
          rSum += c[0]; gSum += c[1]; bSum += c[2];
        }
      }
      if (!cov) continue;
      const i = (y * N + x) * 4;
      out[i] = Math.round((rSum + ink * border[0]) / cov);
      out[i + 1] = Math.round((gSum + ink * border[1]) / cov);
      out[i + 2] = Math.round((bSum + ink * border[2]) / cov);
      out[i + 3] = 255;
    }
  }
  return encodePng(N, out);
}

// ── run ───────────────────────────────────────────────────────────────────
const grid = buildGrid();
const wrote = [];
const write = (rel, buf) => {
  fs.writeFileSync(path.join(ROOT, rel), buf);
  wrote.push(`${rel.padEnd(40)} ${(buf.length / 1024).toFixed(1)} KB`);
};

write('src/renderer/src/brand/logo.svg', Buffer.from(buildSvg(1024, grid, 'mark', BORDERS.ink)));
write('src/renderer/src/brand/logo.png', rasterise(512, grid, 'mark', BORDERS.ink));

console.log(wrote.join('\n'));
